#!/usr/bin/env node

const fs = require('fs');
const path = require('path');
const readline = require('readline');

console.log(`
🏥 StayFit Health Companion - Installation Script
<REDACTED_CREDENTIAL>========

This script will help you configure your StayFit Health Companion installation.
You'll need to provide your AWS Cognito credentials and CloudFront URL.

`);

const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout
});

const config = {
    cognito: {},
    app: {},
    abha: {},
    demo: {}
};

function askQuestion(question) {
    return new Promise((resolve) => {
        rl.question(question, (answer) => {
            resolve(answer.trim());
        });
    });
}

async function collectConfiguration() {
    console.log('📋 AWS Cognito Configuration');
    console.log('-----------------------------');
    
    config.cognito.userPoolId = await askQuestion('Enter your Cognito User Pool ID (e.g., us-region-1_YOUR_USER_POOL_ID): ');
    config.cognito.clientId = await askQuestion('Enter your Cognito Client ID: ');
    config.cognito.clientSecret = await askQuestion('Enter your Cognito Client Secret: ');
    config.cognito.identityPoolId = await askQuestion('Enter your Cognito Identity Pool ID (e.g., your-aws-region:12<REDACTED_CREDENTIAL>-1234-1234-YOUR_AWS_ACCOUNT_ID): ');
    config.cognito.cognitoDomain = await askQuestion('Enter your Cognito Domain (e.g., your-app.auth.your-aws-region.amazoncognito.com): ');
    config.cognito.region = await askQuestion('Enter your AWS Region [your-aws-region]: ') || 'your-aws-region';
    
    console.log('\n🌐 Application URLs');
    console.log('-------------------');
    
    config.app.baseUrl = await askQuestion('Enter your CloudFront URL (e.g., https://YOUR-DOMAIN.cloudfront.net): ');
    config.app.loginUrl = `${config.app.baseUrl}/login.html`;
    config.app.redirectUri = `${config.app.baseUrl}/index.html`;
    
    console.log('\n🏥 ABHA Integration (Optional - for Indian healthcare system)');
    console.log('------------------------------------------------------------');
    
    const enableAbha = await askQuestion('Enable ABHA integration? [y/N]: ');
    if (enableAbha.toLowerCase() === 'y' || enableAbha.toLowerCase() === 'yes') {
        config.abha.clientId = await askQuestion('Enter your ABHA Client ID [demo]: ') || 'demo';
        config.abha.clientSecret = await askQuestion('Enter your ABHA Client Secret [demo]: ') || 'demo';
        config.abha.baseUrl = await askQuestion('Enter ABHA Base URL [https://healthidsbx.abdm.gov.in]: ') || 'https://healthidsbx.abdm.gov.in';
    } else {
        config.abha.clientId = 'demo';
        config.abha.clientSecret = 'demo';
        config.abha.baseUrl = 'https://healthidsbx.abdm.gov.in';
    }
    
    console.log('\n🧪 Demo Configuration');
    console.log('---------------------');
    
    const enableDemo = await askQuestion('Enable demo mode for testing? [Y/n]: ');
    config.demo.enabled = enableDemo.toLowerCase() !== 'n' && enableDemo.toLowerCase() !== 'no';
    
    if (config.demo.enabled) {
        config.demo.testCredentials = {
            email: await askQuestion('Enter demo email [demo@example.com]: ') || 'demo@example.com',
            password: await askQuestion('Enter demo password [YOUR_DEMO_PASSWORD]: ') || 'YOUR_DEMO_PASSWORD'
        };
    } else {
        config.demo.testCredentials = {
            email: 'demo@example.com',
            password = "your_secure_password"};
    }
}

function generateConfigFile() {
    const configContent = `// StayFit Health Companion Configuration
// Generated by installation script on ${new Date().toISOString()}

window.STAYFIT_CONFIG = {
    // AWS Cognito Configuration
    cognito: {
        userPoolId: '${config.cognito.userPoolId}',
        clientId: '${config.cognito.clientId}',
        clientSecret: '${config.cognito.clientSecret}',
        identityPoolId: '${config.cognito.identityPoolId}',
        cognitoDomain: '${config.cognito.cognitoDomain}',
        region: '${config.cognito.region}'
    },
    
    // Application URLs
    app: {
        baseUrl: '${config.app.baseUrl}',
        loginUrl: '${config.app.loginUrl}',
        redirectUri: '${config.app.redirectUri}'
    },
    
    // ABHA Integration (Optional)
    abha: {
        clientId: '${config.abha.clientId}',
        clientSecret: '${config.abha.clientSecret}',
        baseUrl: '${config.abha.baseUrl}'
    },
    
    // Demo/Test Configuration
    demo: {
        enabled: ${config.demo.enabled},
        testCredentials: {
            email: '${config.demo.testCredentials.email}',
            password = "your_secure_password"}
    }
};

// Validation function
window.STAYFIT_CONFIG.validate = function() {
    const required = [
        'cognito.userPoolId',
        'cognito.clientId', 
        'cognito.clientSecret',
        'cognito.identityPoolId',
        'cognito.cognitoDomain',
        'app.baseUrl',
        'app.loginUrl',
        'app.redirectUri'
    ];
    
    const missing = [];
    required.forEach(path => {
        const value = path.split('.').reduce((obj, key) => obj && obj[key], this);
        if (!value || value === 'CONFIGURE_ME') {
            missing.push(path);
        }
    });
    
    if (missing.length > 0) {
        console.error('❌ StayFit Configuration Error: Missing required configuration values:', missing);
        console.error('📋 Please run the installation script to configure these values.');
        return false;
    }
    
    console.log('✅ StayFit Configuration validated successfully');
    return true;
};

// Export for Node.js environments
if (typeof module !== 'undefined' && module.exports) {
    module.exports = window.STAYFIT_CONFIG;
}`;

    // Write to src/web/js/config.js
    fs.writeFileSync('src/web/js/config.js', configContent, 'utf8');
    
    // Also create a backup in root
    fs.writeFileSync('config.js', configContent, 'utf8');
}

function updateHtmlFiles() {
    const htmlFiles = [
        'src/web/index.html',
        'src/web/login.html',
        'src/web/auth-test.html',
        'src/web/digital-analysis.html',
        'src/web/health-reports.html',
        'src/web/import.html',
        'src/web/search.html',
        'src/web/settings.html',
        'src/web/wiki.html'
    ];
    
    htmlFiles.forEach(filePath => {
        if (fs.existsSync(filePath)) {
            let content = fs.readFileSync(filePath, 'utf8');
            
            // Add config.js script tag if not present
            if (!content.includes('src="js/config.js"') && !content.includes('config.js')) {
                // Find the head section and add config.js
                const headEndIndex = content.indexOf('</head>');
                if (headEndIndex !== -1) {
                    const configScript = '    <script src="js/config.js"></script>\n';
                    content = content.slice(0, headEndIndex) + configScript + content.slice(headEndIndex);
                    fs.writeFileSync(filePath, content, 'utf8');
                    console.log(`✅ Added config.js to ${path.basename(filePath)}`);
                }
            }
        }
    });
}

async function main() {
    try {
        await collectConfiguration();
        
        console.log('\n📝 Generating configuration files...');
        generateConfigFile();
        
        console.log('🔧 Updating HTML files...');
        updateHtmlFiles();
        
        console.log('\n✅ Installation completed successfully!');
        console.log('\n📋 Configuration Summary:');
        console.log(`   Cognito User Pool: ${config.cognito.userPoolId}`);
        console.log(`   Application URL: ${config.app.baseUrl}`);
        console.log(`   Demo Mode: ${config.demo.enabled ? 'Enabled' : 'Disabled'}`);
        console.log(`   ABHA Integration: ${config.abha.clientId !== 'demo' ? 'Enabled' : 'Disabled'}`);
        
        console.log('\n🚀 Next Steps:');
        console.log('1. Test the application locally: npm start');
        console.log('2. Deploy to your AWS infrastructure');
        console.log('3. Update your Cognito app client settings with the new redirect URI');
        
        console.log('\n📁 Files created:');
        console.log('   - src/web/js/config.js (main configuration)');
        console.log('   - config.js (backup configuration)');
        
    } catch (error) {
        console.error('❌ Installation failed:', error.message);
        process.exit(1);
    } finally {
        rl.close();
    }
}

// Run the installation
main();
